"""Generate reproducible grouped-CV configs for formal MS1/MS2 ablation."""
from __future__ import annotations

import argparse
from pathlib import Path

import yaml


ABLATION_ARMS = (
    "context_only",
    "ms1_only",
    "ms2_observed_only",
    "ms2_all",
    "ms1_ms2_no_prediction",
    "evidence_all",
    "full",
)
DATASETS = ("2da", "5da", "normal")
DEFAULT_DROP_FEATURES = (
    "spec_pattern_spearman_b",
    "spec_pattern_SA_b",
)


def _experiment_name(dataset, fdr, arm):
    return f"ablation_{dataset}_{fdr}_{arm}"


def build_ablation_config(*, feature_root, output_root, dataset, fdr, arm):
    """Build one fixed-hyperparameter, grouped-CV ablation configuration."""
    feature_root = Path(feature_root)
    output_root = Path(output_root)
    feature_csv = (
        feature_root / f"baseline_{dataset}_{fdr}" / "features.csv")
    name = _experiment_name(dataset, fdr, arm)
    return {
        "data": {
            "train_files": [str(feature_csv)],
            "test_files": [],
            "feature_cols": [],
            "feature_arm": arm,
            "drop_features": list(DEFAULT_DROP_FEATURES),
            "cohort": "evidence_common",
            "target_col": "label",
            "group_col": "sequence",
        },
        "model": {
            "type": "lightgbm",
            "params": {
                "boosting_type": "gbdt",
                "objective": "binary",
                "metric": ["auc", "binary_logloss"],
                "num_leaves": 15,
                "learning_rate": 0.02,
                "feature_fraction": 0.9,
                "bagging_fraction": 0.8,
                "min_data_in_leaf": 50,
                "verbose": -1,
            },
        },
        "training": {
            "num_boost_round": 2000,
            "early_stopping_rounds": 200,
            "valid_size": 0.15,
            "cv_folds": 5,
            "cv_seed": 42,
            "min_class_groups_per_split": 5,
        },
        "output": {
            "model_path": str(output_root / "models" / f"{name}.txt"),
            "result_path": str(output_root / "results" / f"{name}.cv.json"),
        },
        "operating_point": {"target_fpr": 0.10},
        "audit": {"suspect_threshold": 0.9, "suspect_top_n": 200},
    }


def generate_configs(*, feature_root, output_root, config_dir, datasets,
                     arms, fdr):
    """Validate inputs and write the requested matrix in stable order."""
    feature_root = Path(feature_root)
    output_root = Path(output_root)
    config_dir = Path(config_dir)

    missing = [
        feature_root / f"baseline_{dataset}_{fdr}" / "features.csv"
        for dataset in datasets
        if not (feature_root / f"baseline_{dataset}_{fdr}" /
                "features.csv").is_file()
    ]
    if missing:
        formatted = "\n".join(f"  - {path}" for path in missing)
        raise FileNotFoundError(
            f"missing ablation feature CSV files:\n{formatted}")

    config_dir.mkdir(parents=True, exist_ok=True)
    paths = []
    for dataset in datasets:
        for arm in arms:
            cfg = build_ablation_config(
                feature_root=feature_root,
                output_root=output_root,
                dataset=dataset,
                fdr=fdr,
                arm=arm,
            )
            name = _experiment_name(dataset, fdr, arm)
            path = config_dir / f"{name}.yaml"
            with path.open("w", encoding="utf-8") as handle:
                handle.write(
                    "# AUTO-GENERATED by gen_ablation_configs.py; "
                    "regenerate instead of editing.\n")
                yaml.safe_dump(
                    cfg, handle, sort_keys=False, allow_unicode=True)
            paths.append(path)
    return paths


def _parser():
    parser = argparse.ArgumentParser(
        description="Generate formal MS1/MS2 ablation CV configs")
    parser.add_argument("--feature-root", required=True)
    parser.add_argument(
        "--output-root", default="runs/spec_trainer/ablation/neg20")
    parser.add_argument(
        "--config-dir",
        default="runs/spec_trainer/ablation/configs/neg20")
    parser.add_argument("--fdr", default="neg20")
    parser.add_argument(
        "--datasets", nargs="+", choices=DATASETS, default=list(DATASETS))
    parser.add_argument(
        "--arms", nargs="+", choices=ABLATION_ARMS,
        default=list(ABLATION_ARMS))
    return parser


def main(argv=None):
    args = _parser().parse_args(argv)
    paths = generate_configs(
        feature_root=args.feature_root,
        output_root=args.output_root,
        config_dir=args.config_dir,
        datasets=args.datasets,
        arms=args.arms,
        fdr=args.fdr,
    )
    print(f"generated {len(paths)} ablation configs in {args.config_dir}")


if __name__ == "__main__":
    main()
