"""Generate formal evidence-only CV configs from the legacy matrix configs.

Each variant uses the common evaluable cohort and defaults to the
``evidence_all`` arm. ``evidence_core`` is available as a pre-declared compact
paired-evidence sensitivity arm. Input/output roots are configurable so an
immutable external feature snapshot can be trained without copying it.
"""
import argparse
import copy
import glob
import os
from pathlib import Path

import yaml

try:
    from .src.feature_groups import EXPERIMENT_ARMS, FORMAL_DROP_FEATURES
except ImportError:  # Direct script execution from tools/spec_trainer.
    from src.feature_groups import EXPERIMENT_ARMS, FORMAL_DROP_FEATURES

_CFG_DIR = os.path.join(os.path.dirname(__file__), "config")


def _rebase_feature_paths(paths, feature_root):
    """Place ``baseline_*/features.csv`` paths directly under feature_root."""
    root = Path(feature_root)
    rebased = []
    for raw_path in paths or []:
        path = Path(raw_path)
        if not path.parent.name.startswith("baseline_"):
            raise ValueError(
                f"cannot rebase non-baseline feature path: {raw_path!r}")
        rebased.append(str(root / path.parent.name / path.name))
    return rebased


def to_cv_config(src, name, *, feature_root="runs",
                 output_root="runs/spec_trainer", feature_arm="evidence_all"):
    """Transform an in_/cross_test source config dict into its cv_ variant.

    name: source basename (e.g. 'in_2da_clean'); the variant is 'cv_' + name.
    Does NOT mutate src (deep-copies). train_files/test_files/model/target_col
    are preserved; CV keys + formal evidence selection and rooted paths are
    set; figures_dir is dropped.
    """
    if not isinstance(src, dict) or "data" not in src or "training" not in src:
        raise ValueError(
            f"{name}: unexpected config shape (need a dict with 'data' and "
            f"'training' keys)")
    cfg = copy.deepcopy(src)
    cfg["data"]["train_files"] = _rebase_feature_paths(
        cfg["data"].get("train_files"), feature_root)
    cfg["data"]["test_files"] = _rebase_feature_paths(
        cfg["data"].get("test_files"), feature_root)
    cfg["data"].pop("test_size", None)
    cfg["data"]["feature_cols"] = []
    if feature_arm not in EXPERIMENT_ARMS:
        raise ValueError(
            f"unknown feature_arm {feature_arm!r}; expected one of "
            f"{sorted(EXPERIMENT_ARMS)}")
    cfg["data"]["feature_arm"] = feature_arm
    cfg["data"]["drop_features"] = list(FORMAL_DROP_FEATURES)
    cfg["data"]["cohort"] = "evidence_common"
    cfg["data"]["group_col"] = "sequence"
    cfg["data"]["require_complete_arm"] = True
    cfg["training"]["cv_folds"] = 5
    cfg["training"]["cv_seed"] = 42
    cfg["training"]["valid_size"] = 0.15
    cfg["training"]["min_class_groups_per_split"] = 5
    cfg["training"]["num_boost_round"] = 2000
    cfg["training"]["early_stopping_first_metric_only"] = True
    model_params = cfg.setdefault("model", {}).setdefault("params", {})
    model_params["metric"] = ["auc", "binary_logloss"]
    model_params["bagging_freq"] = 1
    model_params["seed"] = 42
    model_params["feature_fraction_seed"] = 42
    model_params["bagging_seed"] = 42
    model_params["data_random_seed"] = 42
    model_params["deterministic"] = True
    model_params["force_col_wise"] = True
    cfg["operating_point"] = {
        "target_fprs": [0.05, 0.10],
        "primary_target_fpr": 0.10,
    }
    cfg["evaluation_semantics"] = {
        "positive_class": "incorrect_identification",
        "stored_label": "1=correct_identification, 0=incorrect_identification",
        "model_score": "trust_score=P(correct_identification)",
        "metric_score": "error_score=1-trust_score",
    }
    cfg["audit"] = {"suspect_threshold": 0.9, "suspect_top_n": 200}
    cv_name = "cv_" + name
    output_root = Path(output_root)
    cfg["output"] = {
        "model_path": str(output_root / "models" / f"{cv_name}.txt"),
        "result_path": str(
            output_root / "results" / f"{cv_name}.cv.json"),
    }
    return cfg


def generate_configs(*, feature_root="runs", output_root="runs/spec_trainer",
                     config_dir=_CFG_DIR, feature_arm="evidence_all"):
    """Generate all 30 configs and return their paths."""
    srcs = sorted(glob.glob(os.path.join(_CFG_DIR, "in_*.yaml"))
                  + glob.glob(os.path.join(_CFG_DIR, "cross_test_*.yaml")))
    config_dir = Path(config_dir)
    config_dir.mkdir(parents=True, exist_ok=True)
    outputs = []
    for path in srcs:
        name = os.path.splitext(os.path.basename(path))[0]
        with open(path) as f:
            src = yaml.safe_load(f)
        cv = to_cv_config(
            src, name, feature_root=feature_root, output_root=output_root,
            feature_arm=feature_arm)
        out = config_dir / f"cv_{name}.yaml"
        with out.open("w", encoding="utf-8") as f:
            f.write(f"# AUTO-GENERATED by gen_cv_configs.py from {name}.yaml — "
                    f"edit the source config, not this file.\n")
            yaml.safe_dump(cv, f, sort_keys=False, allow_unicode=True)
        outputs.append(out)
    return outputs


def _parser():
    parser = argparse.ArgumentParser(
        description="Generate formal evidence-only grouped-CV configs")
    parser.add_argument("--feature-root", default="runs")
    parser.add_argument("--output-root", default="runs/spec_trainer")
    parser.add_argument("--config-dir", default=_CFG_DIR)
    parser.add_argument(
        "--feature-arm", choices=sorted(EXPERIMENT_ARMS),
        default="evidence_all")
    return parser


def main(argv=None):
    args = _parser().parse_args(argv)
    outputs = generate_configs(
        feature_root=args.feature_root,
        output_root=args.output_root,
        config_dir=args.config_dir,
        feature_arm=args.feature_arm,
    )
    print(f"generated {len(outputs)} cv configs in {args.config_dir}")


if __name__ == "__main__":
    main()
